#!/usr/bin/env bash

# for rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# for ruby-build
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"

# for the nice promptline
[ -f "$HOME/.local/dotfiles/bash/shell_promptline.sh" ] && source "$HOME/.local/dotfiles/bash/shell_promptline.sh"

# for direnv
eval "$(direnv hook bash)"

# bashmarks plugin
[ -f "$HOME/.local/dotfiles/bash/plugins/bashmarks/bashmarks.sh" ] && source "$HOME/.local/dotfiles/bash/plugins/bashmarks/bashmarks.sh"

